- README.md
- clay.h
- examples/raylib-sidebar-scrolling-container/main.c
This PR primarily adds a new function `Clay_GetScrollContainerData` that exposes internal scroll position for scroll containers, allowing you to build functionality that hooks into scroll position e.g. scroll bars or "jump to content".
> Expose scroll container data and implement scrollbar example

- clay.h
- examples/clay-official-website/index.html
- examples/clay-official-website/main.c
- renderers/raylib/clay_renderer_raylib.c
- renderers/web/html/clay-html-renderer.html
Couple of things in together:
- Fixed a bug where `CLAY_BORDER_CONTAINER` render commands weren't culled when they were outside the screen, which improves performance on the HTML renderer
- Fixed a bug in alpha handling in the web renderers
- Added scrollbars on desktop to the official website example
- Added a janky but mostly usable rounded rectangle implementation for the raylib renderer
- Other small bug fixes in HTML renderer
> Add scrollbar to official website and improve culling

- README.md
- clay.h
- renderers/raylib/clay_renderer_raylib.c
I made what I believe to be a mistake in naming the internal {x, y, width, height} struct `Clay_Rectangle`.
Unfortunately this is a breaking change if you are referencing the struct by name, but there's too much of an overlap / confusion with the element macro `CLAY_RECTANGLE`, and I would like there to be a clear mental model of "rectangle means the element", so I've renamed the struct to `Clay_BoundingBox`, which is more in line with how it is referred to in render commands anyway.
> Rename Clay_Rectangle to Clay_BoundingBox to prevent confusion

- README.md
- clay.h
- examples/raylib-sidebar-scrolling-container/main.c
- renderers/raylib/clay_renderer_raylib.c
Just doing some cleaning up and standardising of function names.
99% of the changes here are just to the internal private API (prefixed with `Clay__`) and shouldn't be breaking changes.
> Stardardisation work for private API functions

- bindings/odin/examples/clay-official-website/clay-official-website.odin
- bindings/odin/examples/clay-official-website/clay_renderer_raylib.odin
Should fix an apparent memory leak (you allocate a clone of the text in the raylib renderer, however the temp_allocator was never freed)
> [bindings/odin] Fix memory leak in Odin example

- bindings/odin/clay-odin/clay.odin
- properly enforce that the measure text function is a "c" function
- make sure the abi matches for OpenScrollElement and OpenFloatingElement, when compiling this to wasm it would complain that the function signatures did not match because these return a pointer to `Clay_LayoutElement`, I opted to make them return a `rawptr` instead of binding the entire type
> Fix some Odin bindings

- clay.h
Fixes warnings like `clay.h:49:132: warning: __VA_ARGS__ can only appear in the expansion of a C99/C++11 variadic macro` and makes the code match CLAY_BORDER_CONFIG_OUTSIDE_RADIUS
> Don't use __VA_ARGS__ in a non-variadic macro

- examples/raylib-sidebar-scrolling-container/CMakeLists.txt
This change reduces the time of project configuration.
On my machine with decent internet connection, I got these results:
Without shallow clone: `cmake ..  24.75s user 6.55s system 54% cpu 57.140 total`
With shallow clone: `cmake ..  12.41s user 4.48s system 39% cpu 42.758 total`
Thank you for your time and effort!
> Use shallow clone on Raylib

- clay.h
The code measurement text actually expects the array to be zero-ed.
> Initialize text measurement hashmap

- clay.h
This uses the parent's id as seed for the id hash.
Motivation: https://github.com/nicbarker/clay/issues/26
> Add CLAY_LOCAL_ID[I]

- clay.h
- examples/clay-official-website/main.c
- examples/raylib-sidebar-scrolling-container/main.c
- tests/docker-compose.yml
- tests/gcc/9.4/Dockerfile
- tests/run-tests.sh
Older versions of GCC have quite strict rules around constant initializers, as raised in https://github.com/nicbarker/clay/issues/24. This PR fixes the issues for gcc 9.4 and adds a dockerised test for gcc 9.4 on ubuntu 20.4.
> Fix const inits and add docker tests for gcc 9.4 

- .github/workflows/cmake-multi-platform.yml
- CMakeLists.txt
- README.md
- clay.h
- examples/clay-official-website/CMakeLists.txt
- examples/cpp-project-example/CMakeLists.txt
- examples/cpp-project-example/main.cpp
- examples/raylib-sidebar-scrolling-container/CMakeLists.txt
- generator/array_define.template.c
- generator/array_set.template.c
This PR adds support for direct `#include clay.h` in C++20. The changes should be opaque to C and other languages. 
The main set of changes required were:
- Macro around designated initializers because C99 uses `(StructName) { members }` and C++20 uses `StructName { members }`
- Macro `__attribute__((__packed__))` and swap out for `enum : uint8_t` for 1 byte enums
- Reorder all designated initializer fields to be in declaration order, as required by C++20 standard (this was a pain)
- Swap out the C99 hack for detecting the alignment of a type for the supported `alignof` in C++20
> C++20 Support

- clay.h
In some situations `mapItem` in `Clay_SetPointerState` can end up being null which results in to crash (because `elementId` is being accessed on null `mapItem`).
An example of this behaviour can be seen when you have an empty layout with only one text:
```c
Clay_BeginLayout();
CLAY_TEXT(
CLAY_ID("HelloWorldText"), 
CLAY_STRING("Hello World!"),
CLAY_TEXT_CONFIG(
.fontId = FONT_ID_BODY_24, 
.fontSize = 24,
.textColor = {255, 0, 0, 255}
)
);
return Clay_EndLayout();
```
> Fix of a crash when mapItem is null

- clay.h
Wrap mode `NEWLINES` was skipped all the time because of this if condition: 
```c
// Short circuit all wrap calculations if wrap mode is none
if (textConfig->wrapMode == CLAY_TEXT_WRAP_NONE || (containerElement->dimensions.width == textElementData->preferredDimensions.width)) {
```
The second part of the if was always true for text with wrapping mode `NEWLINES`. I added another condition that skips this width check in the case of `NEWLINES`.
Automatic word wrapping (works fine):
Manual line breaks (`\n`) before the fix:
Manual line breaks (`\n`) after the fix:
> [Bug] Fix of broken text NEWLINES wrap mode

- README.md
- clay.h
- examples/raylib-sidebar-scrolling-container/main.c
- renderers/web/canvas2d/clay-canvas2d-renderer.html
- renderers/web/html/clay-html-renderer.html
As suggested by @SogoCZE, this PR switches the concept of `lineSpacing` in `Clay_TextElementConfig` for `lineHeight`. In summary, previously the value added *extra pixels of vertical whitespace between wrapped text lines*, and now it controls the *absolute height (in pixels) of wrapped lines of text*, bringing it more in line with the design of other UI layout systems such as CSS.
> Change lineSpacing text config attribute to lineHeight

- clay.h
Made casting more explicit for better compatibility with different compilers. For instance zig cc was producing errors.  And zig cc relies on some version of clang witch is probably also affected.
> Made casting more explicit for better compatibility with different compilers

- examples/raylib-sidebar-scrolling-container/main.c
Fixes unexpected behavior when clicking on scrollbar with mouse, the view would scroll the opposite direction as it would with touch scroll.
This behavior is unexpected with mouse.
The bug was probably caused by Clay_SetPointerState overriding scrollbarData and using the pointer state as scroll information for the container behind the scrollbar instead using the scrollbarData.
This fixes that behavior by not passing mouse down, when mouse down is captured by scrollbar.
> Fix scroll on mouse down being overriden by touch scroll

- clay.h
To address https://github.com/nicbarker/clay/issues/43 🏄‍♂️
I simply forgot to implement a mechanism for clearing stale items from the text measurement cache 🤦 
This PR introduces a "generation" mechanism for clearing items from the text measurement cache. The TL;DR is:
- A `generation` integer is assigned to text measurement cache items every time they are accessed
- When walking the linked lists of hash map items, any items passed over that are more than a few generations old will be ejected.
- If the measurement cache fills up completely (possible in some circumstances where hashes are very evenly distributed, a TODO here is to figure out ideal bucket size to stop this from happening), just remeasure the text dimensions on the fly (obviously much slower, but shouldn't theoretically …
> Fix an overflow bug in the text measurement cache

- README.md
As a newcomer to the library, I noticed that the examples in the README are not 100% consistent with the actual API anymore.
I've updated the README to reflect the new API where I've noticed the inconsistencies.
> docs: remove some inconsistencies with current API

- clay.h
`CLAY_TEXT` won't work without this.
> Forward declare Clay__OpenTextElement

- clay.h
- examples/cairo-pdf-rendering/CMakeLists.txt
- examples/clay-official-website/CMakeLists.txt
- examples/raylib-sidebar-scrolling-container/CMakeLists.txt
This PR greatly improves the story around capacity overflows in various internal data structures.
Currently there are still some unsolved (but not unsolvable) problems:
- Text will not be rendered if `CLAY_MEASURE_TEXT_CACHE_SIZE` is exceeded.
- The error screen for exceeding `CLAY_MAX_ELEMENT_COUNT` is quite severe and non configurable:
> Improve overflow handling / CLAY_MAX_ELEMENT_COUNT exceeded

- clay.h
As raylib renderer uses CLAY__MIN and CLAY__MAX, I suggest moving those marcos to macros public definitions. Otherwise, it's impossible to compile raylib renderer without `#define CLAY_IMPLEMENTATION`.
> Fix: moved CLAY__MIN and CLAY__MAX to public macros

- clay.h
- examples/clay-official-website/build.sh
- examples/clay-official-website/index.html
- examples/clay-official-website/main.c
This PR adds support for native `overflow: scroll` containers to the HTML renderer, which significantly improves scrolling performance for older devices and safari. 
See it in action right now at https://nicbarker.com/clay
Essentially I'm reversing the source of truth - Clay has a new API to call to query the current scroll position of containers, and it's up to the HTML side to actually perform the scrolling.
This has the natural side effect of creating out of the box support for all types of scrolling and customisation naturally supported by the browser, e.g. configurable scroll speed, support for HOME / END keys, etc.
> Implement native scroll containers in HTML renderer

- clay.h
Match Clay_RenderCommandArray_Get protoypes
This PR helps when using Clay on platforms that aren't x86_64.
> fix: move internal types to stdint specific. 

- README.md
- clay.h
- examples/cairo-pdf-rendering/main.c
- examples/clay-official-website/index.html
- examples/cpp-project-example/main.cpp
- examples/raylib-sidebar-scrolling-container/main.c
- generator/array_add.template.c
- generator/array_add_value.template.c
- generator/array_set.template.c
This PR changes `Clay_Initialize` to require that the user provide a function that Clay can call when it encounters an error.
The current error types include:
```C
typedef enum {
CLAY_ERROR_TYPE_TEXT_MEASUREMENT_FUNCTION_NOT_PROVIDED,
CLAY_ERROR_TYPE_ARENA_CAPACITY_EXCEEDED,
CLAY_ERROR_TYPE_ELEMENTS_CAPACITY_EXCEEDED,
CLAY_ERROR_TYPE_TEXT_MEASUREMENT_CAPACITY_EXCEEDED,
CLAY_ERROR_TYPE_DUPLICATE_ID,
CLAY_ERROR_TYPE_FLOATING_CONTAINER_PARENT_NOT_FOUND,
CLAY_ERROR_TYPE_INTERNAL_ERROR,
} Clay_ErrorType;
```
This is part of work to allow the user to handle the case where clay runs out of space in its internal arena, and needs to reallocate with more memory.
> [Core] Implement Error Handler / Callback

- clay.h
Doesn't fix the `##__VA_ARGS__` warnings, as they aren't easily solved with pure C99.
This only fixes the issues in the public code, more needs to be done to do the same for the implementation.
I guess this does cause an API change in the form of the `Clay_SizingAxis` struct being changed slightly, but I think everyone should be using the macros so it shouldn't matter that much.
> [Core] Fix a couple of standards-compliance issues with C99

- examples/introducing-clay-video-demo/main.c
It would probably be good to check that malloc doesn't fail, but for a simple example like this it should be fine.
> [Examples/Intro] Fix NULL pointer deref due to huuge malloc

- clay.h
This makes it easier to implement keyboard shortcuts that toggle the debug menu while also ensuring that the state does not get out of sync, like when closing the menu via the cross in the top right corner.
> Add Clay_IsDebugModeEnabled()

- clay.h
- examples/SDL2-video-demo/CMakeLists.txt
- examples/cairo-pdf-rendering/CMakeLists.txt
- examples/clay-official-website/CMakeLists.txt
- examples/cpp-project-example/CMakeLists.txt
- examples/introducing-clay-video-demo/CMakeLists.txt
- examples/raylib-sidebar-scrolling-container/CMakeLists.txt
- generator/array_allocate_pointer.template.c
- generator/array_define.template.c
- generator/array_define_slice.template.c
This fixes almost all the C99 compliance issues in the implementation of Clay.
Now the only issues remaining are:
> [Core] Fix more C99 compliance issues

- examples/cpp-project-example/CMakeLists.txt
It seems I made a whoopsie in #123 and edited the CXX flags of the example C++ project. This fixes that.
> [Compilers] C++ projects should use CXX flags

- CMakeLists.txt
- cmake/FindCairo.cmake
- examples/cairo-pdf-rendering/CMakeLists.txt
At least on my OSX system, even with `brew install cairo`, cairo isn't found by the C compiler in the standard locations. Calling `FindPackage` with this FindCairo.cmake script and then explicitly linking and including the library solves the issue.
> [Renderers/Cairo] Add FindCairo.cmake

- clay.h
Clang on Windows defines `_MSC_VER` so using it for the definition of `CLAY_PACKED_ENUM` makes it use `__pragma` with Clang, which it cannot understand. This PR fixes it by replacing `#ifdef _MSC_VER` with `#if defined(_MSC_VER) && !defined(__clang__)`.
> Fixed compilation when using Clang on Windows

- clay.h
While trying to debug the failing test in #118, I realised that this macro can be simplified quite a lot, and it can then also support more than 6 arguments!
> [Core] Simplify CLAY macro

- clay.h
The pointer ```parentItem``` could be NULL after the call to ```Clay__GetHashMapItem()```.
Therefore, I moved code blocks so that ```parentItem``` is checked for NULL before dereferencing.
> [Core] Fix NULL pointer dereference when parent of floating container is invalid ID

- examples/clay-official-website/index.html
- renderers/web/canvas2d/clay-canvas2d-renderer.html
- renderers/web/html/clay-html-renderer.html
This PR fixes the issue when RenderCommand.commandType has garbage if RenderCommand's padding memory is not zeroed.
> [Renderers/Web] treat RenderCommand.commandType as uint8_t instead of uint32_t

- clay.h
The `Clay_LayoutElement` type is not exposed so a function: `uint32_t Clay__GetParentElementId()` is needed.
> Fix local id calculation

- README.md
When working with the documentation/readme file i found a small typo/fault! 
Updated and now it is up to date with the current implementation!
> [Documentation] Updated example for `Clay_SetPointerState`

- README.md
- clay.h
- examples/SDL2-video-demo/main.c
- examples/cairo-pdf-rendering/main.c
- examples/clay-official-website/main.c
- examples/introducing-clay-video-demo/main.c
- examples/raylib-sidebar-scrolling-container/main.c
Supersedes #135.
Removes the use of the GNU extension `##__VA_ARGS__`. There were 2 (technically 3) usages of it:
- `CLAY`: based on the poll I sent in the Discord, calling `CLAY` with no parameters is very uncommon, and if it is needed, you can just use `CLAY(0)`.
- `CLAY_SIZING_{FIT,GROW}`: These macros took a struct before for the min and max, this changes it to take min and max as separate parameters, where max is optional. This also more accurately matches what it says in the README.
> [Core] Remove `##__VA_ARGS__`

- clay.h
This is to address https://github.com/nicbarker/clay/issues/188. It fixes a bug where single character lines terminated by an explicit newline character were not correctly output, and also another bug that was hiding it: text wrapping handling was sometimes bypassed entirely in strings that contained newline characters.
> [Core] Fix text wrapping handling with explicit newline characters

- README.md
- clay.h
Allows clearing the text measurement cache if needed.
> Add a function to reset text measurement cache

- clay.h
cc @hexmaster111
This PR adds an API for querying data about layout elements in Clay's internal hierarchy, starting with bounding boxes (x, y, width, height)
> [Core] Add API to query element bounding boxes

- clay.h
I was getting crashes here with floating point exceptions enabled.
This may not be a good fix but at least the resulting layout looks fine again, I can put together a repro if you think this is the wrong way to do it.
> [Core] Don't divide zero by zero

- examples/SDL3-simple-demo/main.c
- renderers/SDL3/README
- renderers/SDL3/clay_renderer_SDL3.c
Added one of the missing features for the SDL3 renderer.
> [Renderers/SDL3] Add rounded corners rectangle functionality

- examples/SDL3-simple-demo/main.c
- renderers/SDL3/README
- renderers/SDL3/clay_renderer_SDL3.c
Added borders, including rounded borders, one of the missing features for the SDL3 renderer.
Also added examples in the SDL3 example.
> [Renderers/SDL3] Add borders and rounded borders functionality.

- CMakeLists.txt
Makes including the examples optional.  SDL2/SDL3 specifically have long download/build times.  If they aren't being used, then this can dramatically speed up build times.
> [CMake] Make Examples Optional in CMAKE

- clay.h
Normalized usage of `Clay__defaultMaxElementCount` and `Clay__defaultMaxMeasureTextWordCacheCount`
This is important - especially - between calls to `Clay_MinMemorySize()` and `Clay_Initialize()` as there was a bug that caused initialization errors when a non-default value is used (in my case `Clay_SetMaxElementCount(8192*2);`).
Repo:
```
int main(int argc, char* argv[])
{
Clay_SetMaxElementCount(8192 * 2);
uint64_t totalMemorySize = Clay_MinMemorySize();
Clay_Arena clayMemory = Clay_CreateArenaWithCapacityAndMemory(totalMemorySize, malloc(totalMemorySize));
auto ctx = Clay_Initialize(clayMemory, { (float)GetScreenWidth(), (float)GetScreenHeight() }, { HandleClayErrors });
auto next = ctx->internalArena.nextAllocation;
long diff = next - totalMemorySize; //diff will show a negative …
```
> Fix: Clay_MinMemorySize() and Clay_Initialize() now report same memory size when using non-default MaxElementCount

- renderers/SDL2/clay_renderer_SDL2.c
Fixes compilation errors when including the renderer in C++ sources.
> [Renderers/SDL2] Don't take addresses of temporaries.

- clay.h
If the string reference passed to an element id has changed between frames (e.g. moved), then the reference stored in the hash item can become stale. This change makes sure that we're always using the latest value.
> Copy elementId in Clay__AddHashMapItem() in case underlying stringId has changed

- clay.h
`#include <emmintrin.h>` was problematic for my use case as emmintrin.h depends on libc. 
I propose adding a CLAY_DISABLE_SIMD flag to conditionally disable SIMD includes to solve this kind of issues.
> [Core] add CLAY_DISABLE_SIMD flag to conditionally disable SIMD includes

- renderers/SDL2/README
- renderers/SDL2/clay_renderer_SDL2.c
Ports over the existing rounded rectangle-rendering code for the SDL3 renderer to the SDL2 renderer, completing its missing features list.
> [Renderers/SDL2] Add rounded rectangle support to sdl2 renderer; feature-completes sdl2 renderer

- bindings/odin/clay-odin/clay.odin
This is useful for hot-reloading and was missing from the bindings. I don't know how much of the Context you want to expose, but I assume it should be opaque.
> [Bindings/Odin] Add get/set current context method to Odin bindings

- clay.h
[`__JETBRAINS_IDE__`](https://blog.jetbrains.com/clion/2017/02/clion-2017-1-eap-debugger-fixes-ide-macros-and-new-cmake/) is defined within Jetbrains editors like CLion and Rider. This is only defined inside the IDE, and does not affect builds, so we can use it to enable `CLAY_IMPLEMENTATION` to improve debugging & intellisense in this environment. I'm not sure if other IDEs have similar macros, but I figured we could start with this one.
Before:
After:
> Define CLAY_IMPLEMENTATION in Jetbrains IDE

- renderers/SDL2/clay_renderer_SDL2.c
Added a function to create rounded corner borders, in the same fashion as the rounded corner rectangle function.
Changed the border render section to call the new function for the four corners and to account for bounding box being smaller than combined border widths.
Also fixed one typo and added a conditional M_PI define if cmath constant is not present.
Fixes issue [257](https://github.com/nicbarker/clay/issues/257).
> [Renderers/SDL2] add rounded corner borders and fixed maximum radius issues.

- renderers/SDL3/clay_renderer_SDL3.c
SDL_SetRenderDrawBlendMode(renderer, SDL_BLENDMODE_BLEND) enables alpha blending in SDL's renderer. Without this, alpha values in colors won't work properly - everything will be rendered as fully opaque regardless of the alpha value.
> [Renderers/SDL3] Enable sdl3 alpha blending

- renderers/SDL2/clay_renderer_SDL2.c
I oopsied and forgot to make the function static on last PR. Simple fix for [issue 262](https://github.com/nicbarker/clay/issues/262).
> [Renderers/SDL2] Make SDL_RenderCornerBorder static

- README.md
- bindings/odin/examples/clay-official-website/clay-official-website.odin
- examples/raylib-sidebar-scrolling-container/main.c
Some people in Discord were getting confused about this:
I dont think `Image` is meant to be used here but instead `Texture` (as used correctly for the Clay website, etc)
`Image` is on the CPU, `Texture` is on the GPU
Additionally,
`LoadImage()` + `LoadTextureFromImage()` without `UnloadImage()` causes a memory leak
raylib has a separate `LoadTexture()` that does the load+send to gpu+unload for you to simplify this
> [Renderers/Raylib] Convert Image usage to Texture

- bindings/odin/clay-odin/clay.odin
- bindings/odin/examples/clay-official-website/clay-official-website.odin
- bindings/odin/examples/clay-official-website/clay_renderer_raylib.odin
- Adds bindings for all public APIs in clay.h to the Odin bindings.
- Fixes the binding for `Initialize`, it should return a pointer to the
context.
- Use `rawptr` for userdata arguments, it's a more ergonomic type for
this use case.
- Many Odin users build with these flags (-vet -strict-style) and it would turn up errors here. 
It is therefore advised to build libraries to conform to the strictest Odin flags.
- Odin prefers tabs for indentation, but most of the bindings currently do spaces, any reason for this? There is even an Odin flag to strictly check for tabs with `-vet-tabs`
- `clay.UI(}.configure({ id = clay.ID("foo") })` could be made to be `clay.UI()({ id = clay.ID("foo") })`, by just returning the function directly instead of wrapped in a struct, I don't mind the current way …
> [Bindings/Odin] add missing bindings, fix binding, improve ergonomics of userdata, conform to stricter style flags

- clay.h
This PR just ensures that MinMemorySize is accurate according to the `maxMeasureTextWordCacheCount` by ensuring `fakeContext` shares the same value as the `currentContext`. Found this after constantly running out of memory when dynamically adding lots of text.
Thanks for the amazing library!
> Make Clay_MinMemorySize accurate based on word cache count

- bindings/odin/README.md
Updates `bindings/odin/README.md` to reflect the latest changes in the Clay API -- particularly the new element macros.
I had some trouble getting the example code in the `README.md` running and updated it so that it should run correctly now.
This PR also updates the coding style of the example Odin code to more closely match language best practices (`snake_case` for variables, etc.).
> Update `README.md` for Odin bindings to reflect the latest API changes.

- README.md
- clay.h
To support DLL's c methods need to be explicitly exported. I have followed the WASM implementation as close as I could (see notes). These changes were needed to make the C# implementation work.
Some implementation notes:
- C isn't my strongest suit. So, its best this gets double checked this works correctly for non-dll exporting.
- I'm not entirely sure if the fallback `CLAY_DLL_EXPORT(null)` is correct in this case. 
- From my (imperfect) testing these had to be added to the declaration of the methods instead of the implementations like WASM can do, might again be me not fully understanding c macro syntax and that it was conflicting with the WASM macro somehow.
- The internal methods that exist for macros also have these so the implementor can recreate the macros.
> [Compilers] Added DLL macro to support .dll building 

- .github/workflows/cmake-multi-platform.yml
- README.md
- clay.h
These are named CLAY_SID*.
This is based on @Roucou's suggestion in https://github.com/nicbarker/clay/issues/276#issuecomment-2673611334, without changing the public API.
This allows you to re-use and compartmentalise IDs more easily.
> [Macros] Add versions of the CLAY_ID macros that take Clay_String

- README.md
example has one too many `}`. Took me a while to find this.
> [Documentation] fix example in README

- clay.h
When compiling for arm using GCC it would complain about the following code because the argument wasn't correct for `vminq_u32` I have now added a cast (that just reinterprets the type so no overhead) to fix the compile error.
> [Compilers] Fixed SIMD related compile error on some ARM compilers

- examples/win32_gdi/build.ps1
- examples/win32_gdi/main.c
- renderers/win32_gdi/README.md
- renderers/win32_gdi/clay_renderer_gdi.c
What is not done:
- Images
- Rendering Rounded Rectangle borders
- Custom Fonts (font size)
What is done:
- Measure text
- Rectangles (round and square)
- Scissor Mode
- Filled Rectangles
- Text
- Examples
- Working examples and build script
Some Screenshots:
Thanks so much for this amazing lib, feel free to close this if it's not done enough. I am now out of time to continue working on this for a little while, but it is in a very usable state.
> [Renderers\win32_gdi] Create initial WinGDI renderer

- clay.h
Hey Nic,
Very cool project, having fun experimenting with Clay in a UI project 🙂 
Fixes some integer truncation warnings, which prevent using clay with a bunch of compiler warnings enabled, such as `-Wall -Wextra -Wpedantic -Werror`:
1.  `Clay__int32_tArray_GetValue` expects an index of type `int32_t`.
2. `Clay_Arena::nextAllocation` is a uintptr_t, explicitly truncate the return value.
> [Compilers] Fix integer truncation warnings with explicit casts

- renderers/SDL2/clay_renderer_SDL2.c
GCC Complaining about not including math.h still runs without the include, but a wall of "use math.h" is printed
> [Renderers/SDL2] Added explicit include of math.h in SDL2 renderer

- bindings/odin/clay-odin/clay.odin
I guess `_OpenElement` and `_CloseElement` are considered private because in C you will likely always use the provided macro. In Odin however there are no macros and exposing the functions allows creating nice component procedures, i.e.:
```odin
@(deferred_none = clay._CloseElement)
my_button :: proc(id: clay.ElementId) -> bool {
clay._OpenElement()
return clay.ConfigureOpenElement({layout = {padding = clay.PaddingAll(8)}})
}
```
Which can be used like this (without calling the higher-order `clay.UI` function):
```odin
if my_button(clay.ID("Btn")) {
clay.Text("Hellope", clay.TextConfig({textColor = WHITE}))
}
/// instead of:
// my_button would return just a clay.ElementDeclaration here
if clay.UI()(my_button(clay.ID("Btn"))) {
clay.Text("Hellope", clay.TextConfig({textColor = WHITE}))
} …
```
> [Bindings/Odin] expose _OpenElement and _CloseElement

- clay.h
mapItem->boundingBox is accessed before mapItem null check.
> [Core] Guard against hashmap item null dereference

- CMakeLists.txt
This PR will allow to use library in a manner provided below:
```
set(CLAY_INCLUDE_ALL_EXAMPLES OFF)
FetchContent_Declare(
CLAY
GIT_REPOSITORY "https://github.com/Qualadia/clay.git"
GIT_TAG main
GIT_SHALLOW TRUE
GIT_PROGRESS TRUE
)
FetchContent_MakeAvailable(CLAY)
target_link_libraries(${PROJECT_NAME} PRIVATE
clay
)
```
> [Cmake] Basic CMake support for easier import into CMake projects

- renderers/raylib/clay_renderer_raylib.c
Make the type cast explicit to avoid using "-fpermissive".
> [Renderers/Raylib] Add explicit type cast for malloc

- renderers/raylib/clay_renderer_raylib.c
Before / After
<details>
<summary>Code</summary>
```c
void RenderHeaderButton(Clay_String text) {
CLAY({
.layout = {
.sizing = {
.width = CLAY_SIZING_GROW(0),
.height = CLAY_SIZING_GROW(0),
},
.childAlignment = (Clay_ChildAlignment) {CLAY_ALIGN_X_CENTER, CLAY_ALIGN_Y_CENTER},
},
.backgroundColor = (Clay_Color){200, 200, 200, 255},
.cornerRadius = {
.topLeft = 24,
.topRight = 24,
.bottomLeft = 24,
.bottomRight = 24,
},
.border = {
.color = (Clay_Color){255, 0, 0, 200},
.width = (Clay_BorderWidth){
.left = 10,
.right = 10,
.top = 1,
.bottom = 10,
},
},
}) {
CLAY_TEXT(text, CLAY_TEXT_CONFIG({
.textAlignment = CLAY_TEXT_ALIGN_CENTER,
.fontId = 0,
.fontSize = 48,
.textColor = {40, 40, 40, 255},
}));
}
}
```
</details>
> [Renderers/Raylib] fix bottom left corner radius of border

- clay.h
- examples/sokol-video-demo/CMakeLists.txt
This is a reasonably temporary fix for single character text hashes - we'll replace the entire hash function with something like [meowhash](https://github.com/cmuratori/meow_hash) in the near future.
> [Core] Fix a string hash bug with single characters

- README.md
- clay.h
- examples/clay-official-website/main.c
- examples/raylib-sidebar-scrolling-container/main.c
- examples/shared-layouts/clay-video-demo.c
Addresses https://github.com/nicbarker/clay/issues/359
This PR replaces the `.scroll` element configuration field with a more generic `.clip` option.
Clip has the same `.horizontal` and `.vertical` booleans, but also provides a `Vector2 .childOffset` field, which is used to offset the positions of all child elements - essentially the building block for implementing scrolling.
Clay still handles scrolling for you in exactly the same way, with the only difference being that you now need to provide the scroll offset for each element:
```C
// Before
CLAY({
.scroll = { .vertical = true }
});
// After
CLAY({
.clip = { .vertical = true, .childOffset = GetScrollOffset() }
})
```
There are two main motivations behind this PR:
- Previously, it was impossible to enable clipping on an element …
> [Core] Replace .scroll config with .clip

- examples/SDL3-simple-demo/main.c
- renderers/SDL3/clay_renderer_SDL3.c
At the moment, the SDL3 renderer image feature is very inefficient. It expects in `imageData` an `SDL_Surface*`, and then creates an `SDL_Texture*` that is immediately destroyed.
Creating an `SDL_Texture*` every single frame is very inefficient and can kill the framerate. This operation uploads the image data to the GPU, which is a rather slow operation. You usually want to do that only once.
- Modify the image rendering feature so that `imageData` expects an `SDL_Texture*` instead of a `SDL_Surface*`
- Update the SDL3 example to load the sample image as a texture instead of a surface
- Add an example of how to display an image using clay that is not present in the shared layout
> [Renderers/SDL3] Use `SDL_Texture` instead of `SDL_Surface` for images

- clay.h
This updates `Clay__RenderDebugLayoutSizing` to handle more sizing types like `CLAY__SIZING_TYPE_FIXED` and `CLAY__SIZING_TYPE_PERCENT`.
> [Debug] Update `Clay__RenderDebugLayoutSizing` to handle more sizing types.

- README.md
Tiny fix to the README, it seems the anchor to the custom element config section was incorrect
> Fix README: use correct anchor to Clay_CustomElementConfig

- clay.h
In commit https://github.com/nicbarker/clay/commit/970919e1fb4fe095373887fe86a6df2938b30544 compatibility with C99 was broken: `use of an empty initializer is a C23 extension`.
> [Core] restore compatibility with C99

- examples/cairo-pdf-rendering/main.c
- renderers/cairo/clay_renderer_cairo.c
There was some changes in clay function calls, so I changed argument types in cairo renderer + had to add ".chars", ".length" and ".isStaticallyAllocated" to Clay_String toTerminate declarations
> [Renderers/Cairo] Fix cairo renderer and example

- clay.h
Closes #318 .
* Adds struct names to all public structs. This makes it possible to forward-declare the public types without including `clay.h`:
```c
struct Clay_RenderCommandArray;
struct my_clay_context;
void my_clay_renderer(struct my_clay_context*, struct Clay_RenderCommandArray const*); 
```
* Leaves enums untouched for simplicity. Only reason to add names to enums would be for consistency with the other type declarations.
* All examples and bindings should compile with these changes.
> Add struct names to public structs

- clay.h
Very minor issue I just noticed. I've never done open source contribution, so let me know if this is an acceptable way to go about it.
Given that the line `if (layoutElement->dimensions.width != 0 && layoutElement->dimensions.height == 0)` is checking if the height of the layout element is 0, it didn't make sense to me to multiply the height by `1/aspect` because the result would always be 0 anyway, hence my change from "height" to "width".
> [Core] Fix dimension calculation that would always result in 0

- examples/SDL3-simple-demo/CMakeLists.txt
Tags for SDL3 releases are now available in the SDL_ttf repo
> [CMake] Set CMake FetchContent GIT_TAG for SDL_ttf

- bindings/odin/clay-odin/clay.odin
- bindings/odin/examples/clay-official-website/clay-official-website.odin
`SizingFit` and `SizingGrow` now take default parameters instead of having to fill with a default struct. this takes the usage from:
```odin
clay.SizingGrow({})
clay.SizingFit({})
```
to
```odin
clay.SizingGrow()
clay.SizingFit()
```
in the default case
> [bindings/odin] SizingFit and SizingGrow default parameters

- clay.h
- renderers/sokol/sokol_clay.h
The text bounding box width was incorrect because the measurement function was using logical pixels while the rendering function was using physical pixels (scaled by DPI). This caused a mismatch where:
- sclay_measure_text() set font size and letter spacing without DPI scaling
- sclay_render() applied DPI scaling to both font size and letter spacing
- fontstash's fonsTextBounds() returned physical pixel measurements even when given logical pixel sizes, leading to incorrect width calculations
The fix ensures consistent DPI scaling by:
1. Scaling font size and letter spacing by dpi_scale during measurement
2. Dividing the returned bounds by dpi_scale to convert back to logical pixels
3. This ensures Clay receives measurements in logical pixels that match what will actually be rendered
This …
> [Renderers/Sokol] Text measurement/rendering width mismatch in sokol_clay

- renderers/sokol/sokol_clay.h
This code implements the rendering of clay images for the sokol renderer backend.
Previously there was a big todo and the code did nothing. Now it renders the image.
Several caveats :
- I’m not that smart, so I just copy pasted the code to render rectangles and adapted it to provide uv coordinates to a texture. Any bug in the rectangle rendering will be in the image rendering.
- I tried to implement corner radius but couldn’t. Maybe someone smarter than me can figure it out (I might give it a try in the future). So if any cornerRadius is specified, the image will look quite bad. Maybe we should just render a full rectangle all the time instead of a corrupted image ?
- Yet, this is strictly better than before.
- Tinting worked out of the box, which I’m quite happy with.
- I tried to give a …
> [Renderers/Sokol] allow usage of images with sokol renderer

- clay.h
Build fix for CLAY_ID_LOCAL() usage
> fix: unused extra macro param

- clay.h
clay.h: Fix struct with default initializer not using CLAY__DEFAULT_STRUCT
no other changes
> clay.h: Fix struct with default initializer not using CLAY__DEFAULT_STRUCT

- clay.h
Summary from issue [#459](https://github.com/nicbarker/clay/issues/459): If a parent element has multiple floating children, then each child cannot use `Clay_Hovered()` because Clay will report an error, and hovering won't be handled properly.
```
An element with this ID was already previously declared during this layout.
```
I've found that `Clay_Hovered()` uses an anonymous ID for each button, generated from the amount of sibling elements as the offset. However, since floating children are not logically part of their parents, their IDs will not be unique.
My fix makes an element keep track of how many floating children they have to ensure generated anonymous IDs remains unique for each floating child.
https://github.com/user-attachments/assets/4624968c-e5dc-4018-8943-df50e71f0f2a
> [Bug Fix] Multiple Floating Elements Cannot Use `Clay_Hovered()`
